### ISSUE TITLE
Saving an entity more than once adds to the search index instead of replacing it

### ISSUE THREAD

**Issue by mbyrne00** [3wks/spring-boot-gae#4]
When you save an entity with an initial value in a field with a search index, then update that value and save it again you will have two entries in the search index instead of just the new one.

Look for `@Ignore` tests in `StringSearchRepositoryTest`, `LongSearchRepositoryTest` and any other tests with a link to this issue.

Also uncomment assertions for `reindex` when fixing ...
```
//TODO: Uncomment below when issue fixed: https://github.com/3wks/spring-boot-gae/issues/4
```

**Comment by mlev** [comment]
Not an issue - the tests were performing a search and matching on the initial word. i.e. with value "name2 updated" a search for "name2" will return a match. I've updated the tests to reflect the intended behaviour.
